// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgLohrM1NDkf9qj34ihduUOcZXifBRWKg',
    appId: '1:600159883268:web:64d6fdb535cfbf4612a551',
    messagingSenderId: '600159883268',
    projectId: 'task-41454',
    authDomain: 'task-41454.firebaseapp.com',
    storageBucket: 'task-41454.appspot.com',
    measurementId: 'G-TSGZFTB7PV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUNTk2K3URKqwD4rO2aW0SiLoi5hgaQQg',
    appId: '1:600159883268:android:89b1d93a2c93cf6512a551',
    messagingSenderId: '600159883268',
    projectId: 'task-41454',
    storageBucket: 'task-41454.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeG_lo3GK6i3YaP6oFvQ5zoT7lzr5aTfA',
    appId: '1:600159883268:ios:cdb00775e217cbbb12a551',
    messagingSenderId: '600159883268',
    projectId: 'task-41454',
    storageBucket: 'task-41454.appspot.com',
    iosClientId: '600159883268-m4lhu63mvamfnc0n3fuals997ai5f5uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled24',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeG_lo3GK6i3YaP6oFvQ5zoT7lzr5aTfA',
    appId: '1:600159883268:ios:cdb00775e217cbbb12a551',
    messagingSenderId: '600159883268',
    projectId: 'task-41454',
    storageBucket: 'task-41454.appspot.com',
    iosClientId: '600159883268-m4lhu63mvamfnc0n3fuals997ai5f5uc.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled24',
  );
}
