abstract class LoginState {}
class InitState extends LoginState{}
class RememberMe extends LoginState{}
class IsObscure extends LoginState{}
class DataSuccess extends LoginState{}
class DataError extends LoginState{}
class CheckSuccess extends LoginState{}
class CheckLoading extends LoginState{}
class CheckError extends LoginState{}
class PasswordAndEmailAuthSuccess extends LoginState{}
class PasswordAndEmailAuthError extends LoginState{}
class PasswordAndEmailSignInError extends LoginState{}
class PasswordAndEmailSignInSuccess extends LoginState{}